# Generated by Django 6.1.1 on 2026-10-08 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Уникальное название товарной группы', max_length=120, unique=True, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, help_text='Краткая характеристика номенклатурной группы', verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, help_text='Уникальный идентификатор позиции на складе', max_length=50, unique=True, verbose_name='Артикул (SKU)')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Наименование товара')),
                ('unit', models.CharField(choices=[('pcs', 'шт.'), ('kg', 'кг'), ('l', 'л'), ('m', 'м'), ('box', 'упак.')], default='pcs', max_length=10, verbose_name='Единица измерения')),
                ('price', models.DecimalField(decimal_places=2, help_text='Учётная стоимость за одну единицу', max_digits=10, verbose_name='Базовая цена (руб.)')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Фактическое количество товара на складе', verbose_name='Текущий остаток')),
                ('min_quantity', models.PositiveIntegerField(default=5, help_text='Порог для формирования сигнала о дефиците', verbose_name='Минимальный остаток')),
                ('description', models.TextField(blank=True, verbose_name='Описание товара')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['name'],
            },
        ),
    ]
